version: "3"
services:
  app_react:
    build: ./risuto-front
    container_name: app_react
    volumes:
      - build_react:/var/www/html
    environment:
      VITE_API_BASE_URL: 'http://localhost/api'
    depends_on:
      - app_node

  banco:
    image: postgres
    container_name: banco
    ports:
      - 2345:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATABASE: "risuto"
    volumes:
      - volume_banco:/var/lib/postgresql/data

  app_node:
    build: ./risuto-back
    container_name: app_node
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      JWT_SECRET: "docker_secret"
      DATABASE_URL: "postgresql://postgres:123456@banco:5432/risuto?schema=public"
    volumes:
      - ./risuto-back/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm run migration:run && npm run start"
    depends_on:
      - banco

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  build_react:
  volume_banco:
